export const metadata = {
    title: "KeenKeeper | Stats",
    description: "Generated by create next app",
};

const StatsPage = () => {
    return (
        <div>
            <h2>Stats</h2>
        </div>
    );
};

export default StatsPage;
