export const metadata = {
    title: "KeenKeeper | Timeline",
    description: "Generated by create next app",
};

const TimelinePage = () => {
    return (
        <div>
            <h2>Timeline page</h2>
        </div>
    );
};

export default TimelinePage;
